// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoDetectPort(arg1:string):Promise<string>;

export function BuildCommand(arg1:number,arg2:string):Promise<Array<number>>;

export function CancelOperation():Promise<void>;

export function Connect(arg1:string):Promise<main.ConnectionInfo>;

export function Disconnect():Promise<void>;

export function GetCalibrationPlan():Promise<Array<main.CalStepDTO>>;

export function ListSerialCandidates(arg1:string):Promise<Array<string>>;

export function ReReadFactors():Promise<void>;

export function ReadFactorsRaw(arg1:number):Promise<Array<number>>;

export function SendVersion():Promise<string>;

export function StartCalibrationStep(arg1:number):Promise<void>;

export function StartFlash(arg1:string):Promise<void>;

export function StartTest():Promise<void>;

export function StopTest():Promise<void>;
