// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetectPort(arg1) {
  return window['go']['main']['App']['AutoDetectPort'](arg1);
}

export function BuildCommand(arg1, arg2) {
  return window['go']['main']['App']['BuildCommand'](arg1, arg2);
}

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetCalibrationPlan() {
  return window['go']['main']['App']['GetCalibrationPlan']();
}

export function ListSerialCandidates(arg1) {
  return window['go']['main']['App']['ListSerialCandidates'](arg1);
}

export function ReReadFactors() {
  return window['go']['main']['App']['ReReadFactors']();
}

export function ReadFactorsRaw(arg1) {
  return window['go']['main']['App']['ReadFactorsRaw'](arg1);
}

export function SendVersion() {
  return window['go']['main']['App']['SendVersion']();
}

export function StartCalibrationStep(arg1) {
  return window['go']['main']['App']['StartCalibrationStep'](arg1);
}

export function StartFlash(arg1) {
  return window['go']['main']['App']['StartFlash'](arg1);
}

export function StartTest() {
  return window['go']['main']['App']['StartTest']();
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}
